return {
	"folke/which-key.nvim",
	{
		event = "VeryLazy",
		setup = function()
			require("which-key").setup({
				preset = "helix",
				delay = 0,
				icons = {
					rules = {
						{ pattern = "register", icon = " ", color = "yellow" },
						{ pattern = "command", icon = " ", color = "purple" },
						{ pattern = "grep", icon = " ", color = "green" },
						{ pattern = "colorscheme", icon = " ", color = "purple" },
						{ pattern = "theme", icon = " ", color = "purple" },
						{ pattern = "focus", icon = " ", color = "blue" },
						{ pattern = "buffers", icon = "󰈔", color = "cyan" },
						{ pattern = "lsp", icon = " ", color = "blue" },
					},
					mappings = vim.g.have_nerd_font,
					keys = vim.g.have_nerd_font and {} or {
						Up = "<Up> ",
						Down = "<Down> ",
						Left = "<Left> ",
						Right = "<Right> ",
						C = "<C-…> ",
						M = "<M-…> ",
						D = "<D-…> ",
						S = "<S-…> ",
						CR = "<CR> ",
						Esc = "<Esc> ",
						ScrollWheelDown = "<ScrollWheelDown> ",
						ScrollWheelUp = "<ScrollWheelUp> ",
						NL = "<NL> ",
						BS = "<BS> ",
						Space = "<Space> ",
						Tab = "<Tab> ",
						F1 = "<F1>",
						F2 = "<F2>",
						F3 = "<F3>",
						F4 = "<F4>",
						F5 = "<F5>",
						F6 = "<F6>",
						F7 = "<F7>",
						F8 = "<F8>",
						F9 = "<F9>",
						F10 = "<F10>",
						F11 = "<F11>",
						F12 = "<F12>",
					},
				},
				spec = {
					{ "<leader>e", desc = "Show diagnostic" },
					{ "<leader>b", group = "buffer" },
					{ "<leader>c", group = "code" },
					{ "<leader>f", group = "file/find" },
					{ "<leader>g", group = "git" },
					{ "<leader>q", group = "quit" },
					{ "<leader>s", group = "search" },
					{ "<leader>sn", group = "noice" },
					{ "<leader>u", group = "ui" },
				},
				triggers = {
					{ "<auto>", mode = "nxso" },
				},
			})
		end,
	},
}
